USE test;
  
ALTER TABLE users CHANGE COLUMN created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users CHANGE COLUMN updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

SELECT * FROM users;